# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-27 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(default='无', max_length=30)),
                ('blog_category', models.CharField(blank=True, max_length=50)),
                ('pub_date', models.DateTimeField(null=True)),
                ('update_time', models.DateTimeField(null=True)),
                ('blog_content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=10)),
                ('pwd', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blog_user',
            name='blog_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lll.user'),
        ),
    ]
